apiVersion: v1
kind: Service 
metadata:
  name: {{ Release.Name }}-pod-service
  labels:
    env: prod
    owner: DanilKravtsov
spec:
  selector:
    project: {{ Release.Name }}
  ports:
    - name: {{ Release.Name }}-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer