apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web1-Deployment
  labels:
    app : my-k8s1-deployment 
spec:
  replicas: 3
  selector: 
    matchLabels: 
      project: kgb1
  template:
    metadata:
      labels:
        project: kgb1
    spec:
      containers:
        - name: kgb1-web
          image: daisykey08/k8sphpdanil:ver1
          ports:
            - containerPort: 80