apiVersion: v1
kind: Service 
metadata:
  name: my-single-pod-service2
  labels:
    env: prod
    owner: DanilKravtsov
spec:
  selector:
    project: kgb2
  ports:
    - name: app-listener2
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer