apiVersion: v1
kind: Service 
metadata:
  name: my-single-pod-service3
  labels:
    env: prod
    owner: DanilKravtsov
spec:
  selector:
    project: kgb3
  ports:
    - name: app-listener3
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer